-- Öneri beğendim/beğenmedim geri bildirimi tablosu.
-- Uygulama EnsureCreated() kullandığı için mevcut DB'ye yeni tabloyu otomatik eklemez;
-- bu script'i bir kez elle çalıştırın (migration_searchkey.sql ile aynı akış).

CREATE TABLE IF NOT EXISTS "RecommendationFeedbacks" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId"    integer NOT NULL,
    "PerfumeId" integer NOT NULL,
    "Liked"     boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RecommendationFeedbacks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RecommendationFeedbacks_Perfumes_PerfumeId"
        FOREIGN KEY ("PerfumeId") REFERENCES "Perfumes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RecommendationFeedbacks_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_RecommendationFeedbacks_PerfumeId"
    ON "RecommendationFeedbacks" ("PerfumeId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_RecommendationFeedbacks_UserId_PerfumeId"
    ON "RecommendationFeedbacks" ("UserId", "PerfumeId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260604173558_AddRecommendationFeedback', '9.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;
